### ISSUE TITLE
How to access web panel after installation?

### ISSUE THREAD

**Issue by ugintl** [hzcodertr/JasminWebPanel#17]
I am on azure. I have created a ubuntu 18 lts virtual machine.

1. How to access webpanel after installation is complete?

2. How will i cd to jasminwebpanel folder on azure?

3. How to download and extract this project to azure using a command? curl or apt-get

**Comment by saydulk** [comment]
check this video https://www.youtube.com/watch?v=bjAje6em2IU

**Comment by ugintl** [comment]
I followed the tutorial, but not able to access gui. Server is working, jasmin is running

How can I know what is the problem?

**Comment by ugintl** [comment]
I have tried development and production both

**Comment by ugintl** [comment]
Working now. I had to add 8000 port to my azure account

**Comment by saydulk** [comment]
which Linux you are using at azure? you need to have Linux system administration and Python Django related vast experience to run this project development and production both

**Comment by ugintl** [comment]
ok. It is working on development, but not on production

**Comment by ugintl** [comment]
What should be my url? 

On development, I am accessing with http://publicip:8000

**Comment by saydulk** [comment]
that will be your server ip address and port

**Comment by hzcodertr** [comment]
contact me :)

**Comment by hzcodertr** [comment]
> check this video https://www.youtube.com/watch?v=bjAje6em2IU

your video wrong did you add nginx or apache server ??

**Comment by saydulk** [comment]
this video shows only development part. i have used apache server for production which was not shows  that video as https://github.com/hzcodertr/JasminWebPanel/issues/8

**Comment by ugintl** [comment]
@saydulk @hzcodertr I am little confused. I set debug false. I visit ip:port. Nothing happens. Then I cd to jasminwebpanel folder and run `python manage.py runserver [::]:8000`

Then again I visit ipaddr:8000 and now it is working. Debug is false. mysql and apache running. Am I on production or development?

**Comment by hzcodertr** [comment]
you need install apache and set wsgi env
